---
# ref https://github.com/EliverLara/firefox-nordic-theme#manual-installation
- name: Clone firefox-nordic # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/EliverLara/firefox-nordic-theme.git
    dest: "{{ app_firefox_profile_path }}/chrome/firefox-nordic-theme"
    bare: true
    depth: 1

- name: Create userChrome.css
  ansible.builtin.blockinfile:
    path: "{{ app_firefox_profile_path }}/chrome/userChrome.css"
    create: true
    mode: '0664'
    owner: "{{ ansible_env.ANSIBLE_USER }}"
    group: "{{ ansible_env.ANSIBLE_USER }}"
    block: |-
      @import "firefox-nordic-theme\/userChrome.css";

- name: Symlink user.js file
  ansible.builtin.file:
    src: "{{ app_firefox_profile_path }}/chrome/firefox-nordic-theme/configuration/user.js"
    path: "{{ app_firefox_profile_path }}/user.js"
    state: link
