---
- name: Converge app
  hosts: all

  roles:
    # - role: serpro69.workstation.app.appimage # can't run via docker due to dbus issues
    - role: serpro69.workstation.app.discord
      vars:
        app_discord_install_betterdiscord: false # noqa var-naming[no-role-prefix]
    - role: serpro69.workstation.app.firefox
    - role: serpro69.workstation.app.flatpak
      vars:
        app_flatpak_application_ids: # noqa var-naming[no-role-prefix]
          - com.calibre_ebook.calibre
    - role: serpro69.workstation.app.jbtoolbox
