---
- name: Verify theme name is valid
  ansible.builtin.assert:
    that: desktop_gnome_theme is 'Nordic' or
      desktop_gnome_theme is 'Nordic-darker' or
      desktop_gnome_theme is 'Nordic-Polar'

- name: Verify theme icons name is valid
  ansible.builtin.assert:
    that: desktop_gnome_theme_icons is 'Nordic' or
      desktop_gnome_theme_icons is 'Nordic-Darker'

- name: Verify theme cursor name is valid
  ansible.builtin.assert:
    that: desktop_gnome_theme_cursor is 'Nordic-cursors'
