---
- name: Ensure ~/Applications dir
  ansible.builtin.file:
    path: "{{ app_appimage_applications_path }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Unarchive jetbrains toolbox
  ansible.builtin.unarchive:
    src: "{{ _app_jbtoolbox_cdn_url }}"
    dest: "{{ app_appimage_applications_path }}"
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    extra_opts:
      - --strip-components
      - 1

- name: Ensure file permissions
  ansible.builtin.file:
    path: "{{ app_appimage_applications_path }}/jetbrains-toolbox"
    state: file
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
