---
- name: Ensure ~/Applications dir
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Applications"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Unarchive jetbrains toolbox
  ansible.builtin.unarchive:
    src: "{{ _jbtoolbox_cdn_url }}"
    dest: "{{ ansible_env.HOME }}/Applications"
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    extra_opts:
      - --strip-components
      - 1

- name: Ensure file permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Applications/jetbrains-toolbox"
    state: file
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
