---
- name: Get appimagelauncher releases
  ansible.builtin.uri:
    url: https://api.github.com/repos/TheAssassin/AppImageLauncher/releases/latest
  register: _app_appimage_launcher_releases
  changed_when: false
  no_log: true

- name: Get appimagelauncher-lite release for x86_64
  ansible.builtin.set_fact:
    app_appimage_launcher_release: "{{ _app_appimage_launcher_releases.json | to_json | from_json | community.general.json_query(query) | first }}"
  vars:
    query: "assets[?contains(name, 'lite') && ends_with(name, 'x86_64.AppImage')]"

- name: Download appimage launcher
  ansible.builtin.get_url:
    url: "{{ app_appimage_launcher_release.browser_download_url }}"
    dest: /tmp/{{ app_appimage_launcher_release.name }}
    mode: '0755'

- name: Install AppImageLauncher # noqa command-instead-of-shell
  ansible.builtin.shell:
    cmd: "./{{ app_appimage_launcher_release.name }} install"
    chdir: /tmp
    executable: /usr/bin/bash
    creates: "{{ ansible_env.HOME }}/.local/lib/appimagelauncher-lite"
