---
- name: Ensure git is installed
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true
    autoclean: true
  become: true

- name: Get latest appimagelauncher version # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: git ls-remote --refs --sort="version:refname" --tags https://github.com/TheAssassin/AppImageLauncher/ | cut -d/ -f3-|tail -n1
  register: _app_appimage_launcher_version
  changed_when: false
  become: false

- name: Set appimagelauncher version
  ansible.builtin.set_fact:
    app_appimage_launcher_version: "{{ _app_appimage_launcher_version }}"
  become: false

- name: Download appimage launcher
  ansible.builtin.get_url:
    url: "{{ _app_appimage_launcher_download_url }}"
    dest: /tmp/appimagelauncher-lite-{{ app_appimage_launcher_version }}.AppImage
    mode: '0755'
  become: false

- name: Install AppImageLauncher
  ansible.builtin.command:
    cmd: appimagelauncher-lite-{{ app_appimage_launcher_version }}.AppImage install
    chdir: /tmp
    creates: "{{ ansible_env.HOME }}/.local/lib/appimagelauncher-lite"
  become: false
