---
- name: Install discord via flatpak
  when: app_discord_use_flatpak | bool
  ansible.builtin.include_role:
    name: serpro69.workstation.app.flatpak
  vars:
    app_flatpak_application_ids: # noqa var-naming[no-role-prefix]
      - com.discordapp.Discord

- name: Install discord via .deb
  ansible.builtin.apt:
    deb: "{{ _app_discord_deb_installer_url }}"
  when: not app_discord_use_flatpak | bool
  become: true

- name: Download better discord
  ansible.builtin.get_url:
    url: "{{ _app_discord_betterdiscord_appimage_url }}"
    dest: /tmp/
    force: true
    mode: '0755'
    owner: "{{ ansible_env.ANSIBLE_USER }}"
    group: "{{ ansible_env.ANSIBLE_USER }}"
  become: false
  when: app_discord_install_betterdiscord | bool

- name: Pause to manually install better discord
  ansible.builtin.pause:
    prompt: |-
      Please run better discord from /tmp/BetterDiscord-Linux.AppImage before proceeding
      Press Ctrl+C to abort
  when: app_discord_install_betterdiscord | bool
