---
dependency:
  name: shell
  command: ansible-galaxy collection install --force . -p molecule/default/galaxy
  env:
    ANSIBLE_ROLES_PATH: galaxy/roles
    ANSIBLE_COLLECTIONS_PATH: galaxy
    ANSIBLE_LOG_PATH: molecule.log
driver:
  name: docker
platforms:
  - name: ubuntu2004
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    privileged: true
    pre_build_image: true
  - name: ubuntu2204
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    privileged: true
    pre_build_image: true
lint: |
  set -e
  ansible-lint
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: galaxy/roles
    ANSIBLE_COLLECTIONS_PATH: galaxy
    ANSIBLE_VERBOSITY: 1
    ANSIBLE_STDOUT_CALLBACK: yaml
    ANSIBLE_LOG_PATH: molecule.log
verifier:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: galaxy/roles
    ANSIBLE_COLLECTIONS_PATH: galaxy
