---
dependency:
  name: shell
  command: |

    #!/usr/bin/env bash
    set -e
    ansible-galaxy collection install --force . -p molecule/default/galaxy
    ansible-lint
  env:
    ANSIBLE_ROLES_PATH: galaxy/roles
    ANSIBLE_COLLECTIONS_PATH: galaxy
    ANSIBLE_LOG_PATH: molecule.log
driver:
  name: docker
platforms:
  - name: ubuntu2004
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    # fix for app.flatpak (see https://github.com/flatpak/flatpak/issues/3027)
    # see also https://discourse.flathub.org/t/error-running-flatpack-in-dockerfile/1636/4
    # and https://github.com/ansible-community/molecule-docker/issues/17
    # TODO not ideal, might want to explore limiting this to certain capabilities and security_opts instead
    privileged: true
    # capabilities:
      # - SYS_ADMIN
    pre_build_image: false
  - name: ubuntu2204
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      # setting for the platforms' vars
      ubuntu2004:
        ansible_user: ansible
      ubuntu2204:
        ansible_user: ansible
  env:
    ANSIBLE_ROLES_PATH: galaxy/roles
    ANSIBLE_COLLECTIONS_PATH: galaxy
    ANSIBLE_VERBOSITY: 1
    ANSIBLE_STDOUT_CALLBACK: yaml
    ANSIBLE_LOG_PATH: molecule.log
verifier:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: galaxy/roles
    ANSIBLE_COLLECTIONS_PATH: galaxy
