---
# jetbrains mono nerd font curl -OL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz
# jetbrains mono https://github.com/JetBrains/JetBrainsMono
# any of https://input.djr.com/download/ fonts look interesting? (would need to be patched manually)
