---
- name: Ensure flatpak is installed
  ansible.builtin.apt:
    name: flatpak
    state: present
    update_cache: true
  become: true

- name: Add flathub remote for user
  community.general.flatpak_remote:
    name: flathub
    state: present
    method: "{{ app_flatpak_install_method }}"
    enabled: true
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install apps via flatpak
  community.general.flatpak:
    name: "{{ app_flatpak_application_ids }}"
    state: present
    method: "{{ app_flatpak_install_method }}"
    remote: flathub
