---
- name: Ensure flatpak is installed
  ansible.builtin.apt:
    name: flatpak
    state: present
    update_cache: true
  become: true

- name: Add flathub remote for user
  community.general.flatpak_remote:
    name: flathub
    state: present
    method: "{{ app_flatpak_install_method }}"
    enabled: true
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install apps via flatpak
  community.general.flatpak:
    name: "{{ app_flatpak_application_ids }}"
    state: present
    method: "{{ app_flatpak_install_method }}"
    remote: flathub

- name: Set flatpak dir fact
  ansible.builtin.set_fact:
    _app_flatpak_path: >-
      {%- if app_flatpak_install_method == 'user' -%}
        {{ ansible_env_HOME }}/.local/share/flatpak'
      {%- else -%}
        /var/lib/flatpak
      {%- endif -%}

- name: Ensure overrides dir
  ansible.builtin.file:
    path: "{{ _app_flatpak_path }}/overrides"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.ANSIBLE_USER }}"
    group: "{{ ansible_env.ANSIBLE_USER }}"
  become: "{{ app_flatpak_install_method is not 'user' }}"

- name: Copy overrides configs for apps
  ansible.builtin.copy:
    src: files/overrides/{{ item }}
    dest: "{{ _app_flatpak_path }}/overrides/"
    mode: '0664'
    owner: "{{ ansible_env.ANSIBLE_USER }}"
    group: "{{ ansible_env.ANSIBLE_USER }}"
  loop:
    - io.dbeaver.DBeaverCommunity
  become: "{{ app_flatpak_install_method is not 'user' }}"
